version: '3.5'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ~/projects:/var/www/html
    restart: always
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    ports:
      - '5959:3306'
    expose:
      - '5959'
    volumes:
      - my-db:/var/lib/mysql
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5958:5432'
    expose:
      - '5958'
    volumes:
      - my-db:/var/lib/mysql
      - pg-db:/var/lib/postgresql/data
  nginx:
    image: nginx
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/sites/:/etc/nginx/conf.d
    restart: always
volumes:
  my-db:
  pg-db:
